version: '3.1'
services:
  db_prod:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: prod
        POSTGRES_DB: proddb
        POSTGRES_PASSWORD: prod
    ports:
      - 5432:5432
  db_test:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: test
        POSTGRES_DB: testdb
        POSTGRES_PASSWORD: test
    ports:
      - 5433:5432
